version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - spark-cdc
  kafka:
    image: quay.io/debezium/kafka:2.7
    ports:
      - 9092:9092
      - 19092:19092
    depends_on:
      - zookeeper
    networks:
      - spark-cdc
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ZOOKEEPER_CONNECT: "zookeeper:2181"
      BROKER_ID: 1
  mysql:
    image: quay.io/debezium/example-mysql:2.7
    ports:
      - 3306:3306
    networks:
      - spark-cdc
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.0
    ports:
      - 8181:8181
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    networks:
      - spark-cdc
  connect:
    image: quay.io/debezium/connect:2.7
    ports:
      - 8083:8083
    networks:
      - spark-cdc
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=_connect_configs
      - OFFSET_STORAGE_TOPIC=_connect_offsets
      - STATUS_STORAGE_TOPIC=_connect_statuses
      - KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
      - VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://schema-registry:8081
    volumes:
      - ./confluent-libs:/kafka/connect/confluent
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 18080:8080
    networks:
      - spark-cdc
    environment:
      KAFKA_CLUSTERS_0_NAME: cdc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      - kafka
networks:
  spark-cdc:
    driver: bridge